services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin_container
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        volumes:
            - pgadmin_data:/var/lib/pgadmin

    redis:
        image: redis:latest
        container_name: redis_container
        restart: always
        volumes:
            - redis_data:/data

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: redis_commander_container
        restart: always
        environment:
            REDIS_HOSTS: redis_container
        ports:
            - "8081:8081"
        depends_on:
            - redis

    auth-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fastify_auth_container
        restart: always
        environment:
            PORT: 7071
            AUTH_DATABASE_URL: postgresql://postgres:password@postgres:5432/auth
            GENERATE_DATABASE_URL: postgresql://postgres:password@postgres:5432/generate
            BILLING_DATABASE_URL: postgresql://postgres:password@postgres:5432/billing
            GOOGLE_OAUTH_CLIENT_ID: 319099825360-85j9mqfbia25m3mlng0eok5gqhd7eo4t.apps.googleusercontent.com
            GOOGLE_OAUTH_CLIENT_REDIRECT_URI: https://localhost:3000/auth/callback
            REDIS_HOST: redis_container
            REDIS_PORT: 6379
            JWT_SECRET: 9LGI8l52AFJ3MU9zr3EG+eJhCnH/Bh+FDYTPRiuRbd3VRZU+MPMFieJGzaXKR4CUPQbIIMhRmLijjTfOu394pA==
            FRONTEND_URL: http://localhost:3000
        ports:
            - "7071:7071"
        depends_on:
            - postgres
            - redis

volumes:
    postgres_data:
    pgadmin_data:
    redis_data:
