version: "3.8"

services:
    postgres:
        environment:
            POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES_STAGING}
        ports:
            - "${SERVICE_PORT_POSTGRES_STAGING}:5432"

    pgadmin:
        environment:
            PGADMIN_DEFAULT_PASSWORD: ${SERVICE_PASSWORD_PGADMIN_STAGING}
        ports:
            - "${SERVICE_PORT_PGADMIN_STAGING}:80"

    redis:
        ports:
            - "${SERVICE_PORT_REDIS_STAGING}:6379"

    redis-commander:
        ports:
            - "${SERVICE_PORT_REDIS_COMMANDER_STAGING}:8081"

    auth-service:
        environment:
            SERVICE_FQDN_AUTH_SERVICE_7071: /api/auth/v1
            PORT: ${SERVICE_PORT_FASTIFY_STAGING:-7071}
            AUTH_DATABASE_URL: postgresql://postgres:${SERVICE_PASSWORD_POSTGRES_STAGING}@${SERVICE_HOST_POSTGRES_STAGING}:${SERVICE_PORT_POSTGRES_STAGING}/auth
            GENERATE_DATABASE_URL: postgresql://postgres:${SERVICE_PASSWORD_POSTGRES_STAGING}@${SERVICE_HOST_POSTGRES_STAGING}:${SERVICE_PORT_POSTGRES_STAGING}/generate
            BILLING_DATABASE_URL: postgresql://postgres:${SERVICE_PASSWORD_POSTGRES_STAGING}@${SERVICE_HOST_POSTGRES_STAGING}:${SERVICE_PORT_POSTGRES_STAGING}/billing
            SENDGRID_API_KEY: ${SENDGRID_API_KEY_STAGING}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_STAGING}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_STAGING}
            AWS_REGION: ${AWS_REGION_STAGING}
            AWS_BUCKET_NAME: ${AWS_BUCKET_NAME_STAGING}
            AWS_BUCKET_REGION: ${AWS_BUCKET_REGION_STAGING}
            GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID_STAGING}
            GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET_STAGING}
            GOOGLE_OAUTH_CLIENT_REDIRECT_URI: ${GOOGLE_OAUTH_CLIENT_REDIRECT_URI_STAGING}
            JWT_SECRET: ${JWT_SECRET_STAGING}
            FRONTEND_URL: ${FRONTEND_URL_STAGING}
            MODE: staging
        ports:
            - "${SERVICE_PORT_FASTIFY_STAGING:-7071}:7071"
